name: DerpiDL
description: A simple command-line application for downloading Derpibooru images.
version: 1.2.0

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  dio: ^3.0.9
  args: ^1.5.0
  path: ^1.0.0

dev_dependencies:
  pedantic: ^1.8.0
